version: '3'
services:
  couchserver:
    image: couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=pass
    volumes:
      - ./dbdata:/opt/couchdb/data
